### ISSUE TITLE
Update git with the latest code

### ISSUE THREAD

**Issue by Danielv123** [chrisgbk/hotpatch#1]
Also, the changelog years are wrong
https://mods.factorio.com/mod/hotpatch-multimod/changelog

Version: 1.1.9
Date: 27. 6. 2018
  Info:
    - More fire!
    - hotpatch-gui version 1.0.3

and 

Version: 1.1.14
Date: 22. 6. 2018
  Info:
    - Updated internal freeplay to match Factorio 0.17.50
    - hotpatch-gui version 1.0.6

**Comment by chrisgbk** [comment]
Updated; dates will be fixed completely in next version unless I mess something up again.
